config/routes.rb
Rails.application.routes.draw do
  resources :orderable
  # post 'menu', to: 'cart#add'
  get 'cart', to: 'cart#show'
  post 'cart/add', to: 'cart#add'
  post 'cart/remove', to: 'cart#remove'
  get 'search', to: 'menu#search'
  resources :categories
  get 'menu', to: 'menu#index'
  resources :products
  devise_for :users
  resources :reservations
  # get 'home/index', to: 'home#index'
  root 'home#index'
  get 'home/about', to: 'home#about'
  # devise_scope :users do
  #   get '/users/sign_out' => 'devise/sessions#destroy'
  # end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary ">
  <div class="container-fluid">
    <%= link_to 'Restaurant', root_path, class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'About_Us', home_about_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Reservations', reservations_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Menu', menu_path, class:"nav-link" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Cart', cart_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
          <%= link_to 'Order Online', menu_path, class:"nav-link" %>
          </li>
          <% if current_user.admin %>
            <li class="nav-item">
            <%= link_to 'Products', products_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
            <%= link_to 'Categories', categories_path, class:"nav-link" %>
            </li>
          <% end %>
          <li class="nav-item">
            <%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete }, class:"nav-link" %> 
          </li>
          <li class="nav-item">
          <%= link_to 'Edit User', edit_user_registration_path, class:"nav-link" %>
        </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Order Online', new_user_session_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
          <%= link_to 'Sign In', new_user_session_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
          <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Us</h1>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Restaurant home page</p>