config/routes.rb
Rails.application.routes.draw do
  resources :orderable
  # post 'menu', to: 'cart#add'
  get 'cart', to: 'cart#show'
  post 'cart/add', to: 'cart#add'
  post 'cart/remove', to: 'cart#remove'
  get 'search', to: 'menu#search'
  resources :categories
  get 'menu', to: 'menu#index'
  resources :products
  devise_for :users
  resources :reservations
  # get 'home/index', to: 'home#index'
  root 'home#index'
  get 'home/about', to: 'home#about'
  # devise_scope :users do
  #   get '/users/sign_out' => 'devise/sessions#destroy'
  # end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/reservation.rb
class Reservation < ApplicationRecord
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: %i[ show edit update destroy ]

  # GET /reservations or /reservations.json
  def index
    @reservations = Reservation.all
  end

  # GET /reservations/1 or /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations or /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to reservation_url(@reservation), notice: "Reservation was successfully created." }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1 or /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to reservation_url(@reservation), notice: "Reservation was successfully updated." }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1 or /reservations/1.json
  def destroy
    @reservation.destroy!

    respond_to do |format|
      format.html { redirect_to reservations_url, notice: "Reservation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reservation_params
      params.require(:reservation).permit(:name, :phone, :resdate, :restime, :people)
    end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<%= form_with(model: reservation) do |form| %>
  <% if reservation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
        <% reservation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class:"form-control" %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone, class:"form-control" %>
  </div>

  <div>
    <%= form.label :resdate, style: "display: block" %>
    <%= form.date_field :resdate, class:"form-control" %>
  </div>

  <div>
    <%= form.label :restime, style: "display: block" %>
    <%= form.time_field :restime, class:"form-control" %>
  </div>

  <div>
    <%= form.label :people, style: "display: block" %>
    <%= form.number_field :people, class:"form-control" %>
  </div>
  <br>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/reservations/_reservation.html.erb
<div id="<%= dom_id reservation %>", class="card">
  <div class="card-body">
    <p>
    <strong>Name:</strong>
    <%= reservation.name %>
    </p>
    <p>
    <strong>Phone:</strong>
    <%= reservation.phone %>
    </p>
    <p>
    <strong>Resdate:</strong>
    <%= reservation.resdate %>
    </p>
    <p>
    <strong>Restime:</strong>
    <%= reservation.restime %>
    </p>
    <p>
    <strong>People:</strong>
    <%= reservation.people %>
    </p>
  </div>
</div>

app/views/reservations/edit.html.erb
<h1>Editing reservation</h1>

<%= render "form", reservation: @reservation %>

<br>

<div>
  <%= link_to "Show", @reservation, class:"btn btn-primary btn-sm" %> |
  <%= link_to "Back", reservations_path, class:"btn btn-primary btn-sm" %>
</div>

app/views/reservations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Reservations</h1>

<div id="reservations" class="row row-cols-auto justify-contents-evenly">
  <% @reservations.each do |reservation| %>
    <div class="col-auto justify-contents-evenly">
      </br>
      <%= render reservation %>
      <p>
        <%= link_to "Show", reservation,  class:"btn btn-primary btn-sm" %>
      </p>
    </div>
  <% end %>
</div>

<%= link_to "New reservation", new_reservation_path, class:"btn btn-primary btn-sm" %>

app/views/reservations/new.html.erb
<h1>New reservation</h1>

<%= render "form", reservation: @reservation %>

<br>

<div>
  <%= link_to "Back", reservations_path, class:"btn btn-primary btn-sm" %>
</div>

app/views/reservations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @reservation %>

<div>
  <%= link_to "Edit", edit_reservation_path(@reservation), class:"btn btn-primary btn-sm" %> |
  <%= link_to "Back", reservations_path, class:"btn btn-primary btn-sm" %>

  <%= button_to "Destroy", @reservation, method: :delete, class:"btn btn-danger btn-sm" %>
</div>